name: untitled
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  #sdk: '>=2.18.5 <3.0.0'
  #sdk: '>=2.12.0 <3.0.0'
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.1+1
  get: ^4.6.5
  google_sign_in: ^6.0.2
  firebase_core: ^2.0.0
  firebase_auth: ^4.3.0
  flutter_login_facebook: ^1.7.0
  flutter_facebook_auth: ^5.0.8
  cloud_firestore: ^4.4.5
  sqflite: ^2.2.8
  path: ^1.8.2
  shared_preferences: ^2.1.0
  conditional_builder_null_safety: ^0.0.6
  image_picker: ^0.8.7+4
  firebase_storage: ^11.1.1
  http: ^0.13.5
  charts_flutter: ^0.12.0 # or another version that has a dependency on intl ^0.16.1
  intl: ^0.17.0
  flutter_native_splash: ^2.2.17
  flutter_launcher_icons: ^0.12.0
  #flutter_charts: ^0.5.1
  flutter_screenutil: ^5.7.0



flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/th.png"
  android_gravity: fill
  android: true
  ios: true
  web: false


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/th.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - imagies/262402791_2647195312093247_4225321798419732059_nm.png
    - imagies/262402791_2647195312093247_4225321798419732059_nmm.png
    - assets/google-plus-svgrepo-com.svg
    - assets/facebook-svgrepo-com.svg
    - imagies/269969424_655870578924985_1432197706298581466_nn.png
    - imagies/Ellipse5.png
    - imagies/aa.jpg
    - imagies/icons8-edit-profile-24.png
    - imagies/icons8-log-out-25.png
    - imagies/icons8-history-24.png
    - imagies/icons8-globe-24.png
    - imagies/icons8-location-24.png
    - imagies/icons8-camera-50.png
    - imagies/undraw_empty_cart_co35.svg
    - imagies/undraw_wishlist_re_m7tv.svg
    - imagies/undraw_Image_upload_re_w7pm.png
    - imagies/icons8-shopping-cart-32.png
    - imagies/shooting-star-and-moon-phone-wallpaper-background.jpg
    - imagies/269969424_655870578924985_1432197706298581466_n.jpg
    - assets/th.png
    - imagies/icons8-in-transit-24.png
    - imagies/delivery-status.png
    - imagies/exchange-rate.png
    - imagies/order.png
    - imagies/order-delivery.png
    - imagies/refund.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
